language: node_js
node_js: "10"

os: osx

notifications:
    email:
        on_success: change # default: change
        on_failure: change # default: always

env:
    global:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# branches:
#     only:
#         - master

cache:
    directories:
        - $HOME/.cache/electron
        - $HOME/.cache/electron-builder
        - yarn
        - node_modules
script:
    - echo "skipping tests"

jobs:
    include:
        - stage: Build
          name: "Build"
          script:
              - yarn run build
          before_cache:
              - rm -rf $HOME/.cache/electron-builder/wine/wine-2.0.3-mac-10.13/wine-home/system.reg
              - rm -rf $HOME/.cache/electron-builder/wine/wine-2.0.3-mac-10.13/wine-home/user.reg
        - stage: Release to Github
          name: Release to Github
          if: branch = master and type != pull_request
          script:
              - yarn run semantic-release
          before_cache:
              - rm -rf $HOME/.cache/electron-builder/wine/wine-2.0.3-mac-10.13/wine-home/system.reg
              - rm -rf $HOME/.cache/electron-builder/wine/wine-2.0.3-mac-10.13/wine-home/user.reg
