language: node_js
node_js: "10"

env:
    global:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branches:
    only:
        - master

matrix:
    include:
        - os: osx
          osx_image: xcode9.4

        - os: linux

cache:
    directories:
        - node_modules
        - $HOME/.cache/electron
        - $HOME/.cache/electron-builder

script:
    - yarn config set version-tag-prefix "v"
    - yarn config set version-git-tag false
    - yarn version --new-version 0.0.$TRAVIS_BUILD_NUMBER
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run publish; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run publish --mac --win; fi

before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine
