theme: jekyll-theme-cayman

description: A net worth tracker

show_downloads: "true"

github:
  windows_download: https://github.com/AnkurSheel/Newt/releases/download/v1.3.2/Newt-Setup.exe
  mac_download: https://github.com/AnkurSheel/Newt/releases/download/v1.3.2/Newt-mac.dmg
  # linux_download: https://github.com/AnkurSheel/Newt/releases/download/v1.1.2/Newt-linux.AppImage

plugins:
  - jekyll-feed

# Google Analytics
google_analytics: UA-140801884-1
