strategy:
    matrix:
        linux:
            imageName: "ubuntu-16.04"
        mac:
            imageName: "macos-10.13"
        windows:
            imageName: "vs2017-win2016"

pool:
    vmImage: $(imageName)

steps:
    - script: echo Hello, world! $(imageName)
    - task: UsePythonVersion@0
      displayName: "Use Python 2.x"
      inputs:
          versionSpec: 2.x
    - task: UsePythonVersion@0
      displayName: "Use Python 2.x"
      inputs:
          versionSpec: 2.x
    - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
      displayName: 'Yarn install'

