strategy:
    matrix:
        # linux:
        #     imageName: "ubuntu-16.04"
        mac:
            imageName: "macos-10.13"
        windows:
            imageName: "vs2017-win2016"

pool:
    vmImage: $(imageName)

steps:
    - script: |
          echo Hello, world! $(imageName)
          echo Hello, world! $(System.DefaultWorkingDirectory)
    - task: NodeTool@0
      displayName: "Use Node 10.x"
      inputs:
          versionSpec: 10.x

    - task: UsePythonVersion@0
      displayName: "Use Python 2.x"
      inputs:
          versionSpec: 2.x

    - script: npm install
      displayName: Install dependencies

    - script: npm run build
      displayName: Build application

    - task: CopyFiles@2
      inputs:
          SourceFolder: "$(System.DefaultWorkingDirectory)"
          Contents: |
              build/*
              package.json
          TargetFolder: "$(Build.ArtifactStagingDirectory)"

    - task: PublishBuildArtifacts@1
