strategy:
    matrix:
        linux:
            imageName: "ubuntu-16.04"
        mac:
            imageName: "macos-10.13"
        windows:
            imageName: "vs2017-win2016"

pool:
    vmImage: $(imageName)

steps:
    - script: echo Hello, world! $(imageName)
    - task: NodeTool@0
      displayName: "Use Node 10.x"
      inputs:
          versionSpec: 10.x

    - task: UsePythonVersion@0
      displayName: "Use Python 2.x"
      inputs:
          versionSpec: 2.x

    - script: npm install
    - script: npm run build
